### ISSUE TITLE
Upstream/remove blobfish.patch

### ISSUE THREAD

**Issue by adam-urbanczyk** [conda-forge/occt-feedstock#108]
### Comment:

Could the `blobfish.patch` be upstreamed to OCCT or removed? It is causing some subtle issues when it comes to packaging and mixing conda-forge and non-conda-forge packages. See https://github.com/CadQuery/OCP/issues/139

CC: @looooo , @blobfish, @efferre79

**Comment by efferre79** [comment]
the patch has been introduced in the @blobfish occt repository [here](https://gitlab.com/blobfish/occt/-/commit/2afb2e25c74d8ca4dbfd57051e73742a0897cbd0), if that patch is strictly needed then I would strongly suggest to submit it for integratation upstream otherwise is only causing conflicts between upstream opencascade and conda-forge one

**Comment by blobfish** [comment]
Yes, having the changes merged upstream would be ideal. However that would require me signing the OpenCasCade CLA and I refuse to do that, so here we are. You guys should stick to using the official branch or my branch and not a hybrid. FYI: my 7.8.0 branch will be pushed soon as I was waiting for them to publish the updated data for the test suite.

**Comment by efferre79** [comment]
Just to have a complete picture, what is the purpose of that patch? Moreover is `IsTangentFaces()` overloading used only by the software in your repositories or is there any other project outside?

**Comment by blobfish** [comment]
I think [commit](https://gitlab.com/blobfish/occt/-/commit/2afb2e25c74d8ca4dbfd57051e73742a0897cbd0) message answers these questions doesn't it?

purpose is: Allow blending of faces less than 5 degrees

IsTangentFaces() overloading used only by the software in your repositories: No, I added the overload only for opencascade itself.

**Comment by efferre79** [comment]
As this feedstock aims to provide upstream OCCT and the patch doesn't solve any open bug (e.g. a backport from a newer version), I would vote for removing it. This to avoid unexpected problems downstream.

**Comment by blobfish** [comment]
The commit in question builds on linux to this day and last year built on multiple versions of mac, windows and linux. I have no idea what you guys have going on here or why a minor change, like adding an overload, would cause you grief. To be 'frank', I don't care enough to investigate. I just made the changes and made them public, I didn't bring the changes to this project.

Yes, you should remove any/all my commits. Then stick to the official opencascade branch, as you will not want to reconcile my changes vs the official branch.

**Comment by blobfish** [comment]
Sorry I didn't mean to get confrontational. Working with OpenCasCade is a huge source of frustration. I think we are on the same page now.

Ok. I have little need/interest in python and language bindings. For people with those needs/interests, they should avoid anything of mine.

**Comment by whophil** [comment]
It is definitely confusing that the `occt` package on conda-forge contains source patches beyond changes which make it possible to _build_ on conda-forge.

Perhaps @looooo or @adrianinsaval can provide some background about why "blobfish" patches (and others) were included in this feedstock? I assume it is related to usage of `occt` in `freecad`?

From the conda packaging perspective, there are a number of ways to resolve this:
- Separate feedstock for "official" and "patched" variants
- One multi-output feedstock (variants with and without patches)

**Comment by adrianinsaval** [comment]
there are several bugfixes relevant to freecad on the blobfish patches, but it might be worth looking at each individually and cherry pick only those that are important

**Comment by adam-urbanczyk** [comment]
@blobfish would you accept some EUR donation to actually upstream your patch or transfer the copyright to someone who would do that? I think it would benefit the whole community...

**Comment by whophil** [comment]
> there are several bugfixes relevant to freecad on the blobfish patches, but it might be worth looking at each individually and cherry pick only those that are important

Thanks @adrianinsaval. I wonder if this feedstock provides a version of OpenCascade that is sufficiently different from the upstream that it should be called something else - e.g., `occt-freecad` - assuming these changes are for the FreeCAD project.

I wonder about the licensing and attribution of the patches. I'm not an expert in that area, though.

There are certainly downstream projects that would prefer to have the "true" upstream `occt` package as well. Having two variants could let developers pick the one their application needs.

**Comment by efferre79** [comment]
> There are certainly downstream projects that would prefer to have the "true" upstream `occt` package as well. Having two variants could let developers pick the one their application needs.

I like the idea of variants if the patch should be preserved.

> there are several bugfixes relevant to freecad on the blobfish patches, but it might be worth looking at each individually and cherry pick only those that are important

The patch is currently a single file merging different commits from blobfish fork and there is no immediate evidence of which problems are solved (from the user point of view). In case you decide to maintain the patch or a subset of it, I would suggest to divide it in separate files, one for each commit or topic (in case there is a series of commits on a specific issue) and to document the problem solved (e.g. a link to the freecad forum, bugs, source commits, etc). The documentation helps with the "consumers" and provides the proper credits to the original author.

BTW if you look in freecad sources, the building system uses opencascade present in the system which typically is not installed by conda (at least on Linux). So there is no way to bind freecad with a specific patched version of opencascade. By just assuming that freecad would be built against this package it is not a good practice in my opinion (different freecad users would get nonidentical experience).

**Comment by whophil** [comment]
> BTW if you look in freecad sources, the building system uses opencascade present in the system which typically is not installed by conda (at least on Linux).

This is the conda-forge OCP feedstock, so I am only taking about conda-forge builds of `freecad`

**Comment by blobfish** [comment]
Sorry, I know my reluctance to sign the OpenCasCade CLA is causing people grief. If I thought it was possible to play nice with corporations, I would still be writing c++ plugins for a high tier CAD system and making a nice living instead of living in poverty. If OpenCasCade wants to start a non-profit foundation, I would seriously consider signing a CLA with that entity, but never a for profit, private company. 

I have never made an official fork. I have a branch of 20 commits(at this time) that I rebase upon new OpenCasCade releases. Packaging probably shouldn't consider anything other than an official fork. At this point, I suggest leaving my branch for people willing to compile it.

A lot of 'FreeCAD' flowing around this thread. I did some work on freecad years ago and still participate in the forum, but I am not involved in the project anymore. So if you guys go against my recommendations and create a separate package, I ask you to not include 'FreeCAD' in the name.  If you want a cad system in the name use occt-[cadseer](https://gitlab.com/blobfish/cadseer/-/wikis/screenshots) or occt-blobfish as there maybe some recognition to my screen name.

**Comment by adam-urbanczyk** [comment]
OK, your position is clear @blobfish 
@looooo what is your take on this, would you consider making this a "clean" occt feedstock?

**Comment by adrianinsaval** [comment]
https://github.com/conda-forge/occt-feedstock/pull/111 I'll start by separating each patch and remove only the problematic one mentioned here. I think the rest of the patches are fine

**Comment by whophil** [comment]
bumping @looooo again, would be great to get your take on this!

**Comment by adrianinsaval** [comment]
I merged the PR as a first step before too many packages get rebuilt against occt 7.8.1

**Comment by adam-urbanczyk** [comment]
> I merged the PR as a first step before too many packages get rebuilt against occt 7.8.1. I'm leaning towards leaving the remaining patches in but I'm open to suggestions.

Works for me, thanks!

**Comment by adam-urbanczyk** [comment]
Solved by #111
