### ISSUE TITLE
remove some problematic uploads

### ISSUE THREAD

**Issue by looooo** [conda-forge/occt-feedstock#11]
@conda-forge-admin
I have made some mistakes, and there were some problematic packages uploaded:
- win-64/occt-7.1.0-occt7.0.0_vc14_0.tar.bz2
- win-32/occt-7.1.0-occt7.0.0_vc14_0.tar.bz2
- linux-64/occt-7.1.0-occt7.0.0_0.tar.bz2

The version of the track-feature and the version it self are not the same. It would be great if these files could be removed.

https://anaconda.org/conda-forge/occt/files

**Comment by looooo** [comment]
@conda-forge-coordinator

**Comment by isuruf** [comment]
Done. @looooo, please in the core team `conda-forge/core`. @conda-forge-coordinator and @conda-forge-admin are just bots.

**Comment by looooo** [comment]
thanks.
