### ISSUE TITLE
Unable to get previous 7.2.0 version from conda Windows 64-bit

### ISSUE THREAD

**Issue by trelau** [conda-forge/occt-feedstock#15]
@looooo It seems recently there is a new 7.2.0-1 version without draw.exe and a few other changes like upgrading to freetype 2.8 (previous was 2.7). The original occt 7.2.0 was compatible with a version of VTK I was using (7.1.1) in a Python wrapping project ([pyOCCT](https://github.com/LaughlinResearch/pyOCCT)) since they both used the same version of freetype. Now I get compatibility issues with 7.2.0-1, but that's ok if I could still target the original 7.2.0 in the conda environment in the short term. I've tried something like:

```
conda install -c conda-forge occt=7.2.0=vc14_0
```

and it says it can't find the package. I think I've used that syntax for other packages, and

```
conda install -c conda-forge occt=7.2.0=1
```

seems to target that latest build. Am I missing something obvious in conda or is there an issue with accessing that previous version?

Update:
When I do:

```
conda search -c conda-forge occt=7.2.0=occt7.2.0_vc14_0
```

it seems to find the package but not when I switch to the install command.

**Comment by looooo** [comment]
I disabled draw-exe, because it depends on tk and I couldn't figure out how to build with tk on mac. But as travis fails anyway (build needs too much time) I can try to enable drawexe again. 

```it seems to find the package but not when I switch to the install command.```
I wasn't aware anyone already uses the occt package, so sorry for introducing the problem. The doubled feature seems to be a problem for conda anyway, so deleting the features was maybe a good decision. Is it somehow possible to make the latest version work for you?
For FreeCAD I am now using all the latest pinnings from conda-forge. Maybe it would be possible for you to update to these versions too? (vtk8, ...)

> Python wrapping project (pyOCCT)
Nice to see this new project! Is it ok if I announce it on the FreeCAD-project. I think this will have a big impact for FreeCAD too.

**Comment by trelau** [comment]
Thanks for the info. Yes I'll try and upgrade to the latest conda-forge libraries like VTK8 and see if I can proceed that way. Feel free to share the pyOCCT project as you wish, it's a young project so expect some churn early on.

**Comment by trelau** [comment]
It looks like VTK 8.1.0 conda-forge still uses freetype 2.7 so I get some compatibility issues with occt 7.2.0-1 and freetye 2.8.1. Can you use freetype 2.7? I know this isn't an occt problem, but rather smesh/vtk issue, but I was hoping to avoid forking everything and making my own builds.

**Comment by looooo** [comment]
conda-forge definetly pins 2.8.1:
https://github.com/ocefpaf/conda-forge.github.io/blob/master/scripts/pin_the_slow_way.py#L75

so reverting this is not the way to go I guess. But I can have a look into updating vtk dependencies:
https://github.com/conda-forge/vtk-feedstock/pull/49

To make a temporary fix, I guess the simplest way is to pull the occt-repo build it locally and push it to your conda-channel. But normally conda-forge is quite fast in accepting version updates. So maybe it's worth to wait for a week or so.

**Comment by trelau** [comment]
Agreed, and thanks. I'll close this issue since it is a vtk issue and not occt.

**Comment by looooo** [comment]
@trelau 
btw.: the better option for sure:

1. Clone the vtk-feedstock
2. Update version (don't update the buid nr) 
3. push package to your channel

this way the package from your channel (channel with higher priority) with the fix will be used. Once a build with a newer build number is available at conda-forge the dependency-solver witll use this package.
