### ISSUE TITLE
remove package with wrong sources

### ISSUE THREAD

**Issue by looooo** [conda-forge/occt-feedstock#16]
@conda-forge/core

The latest 3 packages of [occt](https://anaconda.org/conda-forge/occt/files) use wrong source (beta version of occt), so please delete them:
- win-32/occt-7.2.0-1.tar.bz2
- linux-64/occt-7.2.0-1.tar.bz2
- win-64/occt-7.2.0-1.tar.bz2

I will update the builds after I tested them in user-channel.

**Comment by looooo** [comment]
related issue: https://github.com/conda-forge/occt-feedstock/issues/15

**Comment by ocefpaf** [comment]
Done. Please check if I got them right:  https://anaconda.org/conda-forge/occt/files

**Comment by looooo** [comment]
perfect, thanks.
