### ISSUE TITLE
travis needs more build time

### ISSUE THREAD

**Issue by looooo** [conda-forge/occt-feedstock#17]
@conda-forge/core

building on travis doesn't work because too much time is neeeded. Looking at the logs we need only a view minutes more.
Is there a way to allow more build-time?

**Comment by scopatz** [comment]
Unfortunately, build time is set by the CI services...

**Comment by scopatz** [comment]
I can try to do a manual build on my build machine and upload it if you want to disable the mac build and merge it to master

**Comment by looooo** [comment]
that would be fantastic. I will try to add some fixes and inform you once that is done.

**Comment by isuruf** [comment]
conda-build=3.5 has some fixes that makes the fixing linking step really fast. I've started a build here, https://travis-ci.org/conda-forge/occt-feedstock/builds/349000502. Let's see how that goes.

**Comment by jakirkham** [comment]
Might also consider using `nmake` instead of `make`.

**Comment by looooo** [comment]
thanks @isuruf @jakirkham 
rerendering with conda-smithy 3.0 didn't worked either. I have made a PR where I build with ninja on all platforms: https://github.com/conda-forge/occt-feedstock/pull/19

**Comment by jakirkham** [comment]
Something else that could help is checking to make sure nothing unnecessary is being built. For example, discovered the other day that we were building benchmarks for a package, which we don’t need. Another example might be if the package builds a vendored copy of its dependencies instead of using equivalents in cf.

**Comment by looooo** [comment]
hmm I don't know where we can simplify the recipe. I guess it is already a minimalistic build.
OSX is disabled again as ninja and conda-smithy3 didn't helped. But thanks anyway.

**Comment by looooo** [comment]
@scopatz PR is merged: https://github.com/conda-forge/occt-feedstock/pull/19
it would be nice if you find some time for a osx package.  This would be a nice addition ; )

used in:
- https://github.com/conda-forge/staged-recipes/pull/5320
- https://github.com/conda-forge/staged-recipes/issues/5179

**Comment by scopatz** [comment]
hmmm it seems that this is skipped for Python v3.6.  Is a 3.6 build not possible for some reason?

```console
anthony@asmac ~/feedstocks/occt master $ conda build recipe/
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Skipped: occt from /Users/anthony/feedstocks/occt/recipe defines build/skip for this configuration ({'python': '3.6'}).
# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:


# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

anaconda_upload is not set.  Not uploading wheels: []
####################################################################################
Resource usage summary:

Total time: 0:00:32.3
CPU usage: sys=0:00:00.0, user=0:00:00.0
Maximum memory usage observed: 0B
Total disk usage observed (not including envs): 0B
```

**Comment by looooo** [comment]
thanks for having a look at this. 

osx is skipped to not build with travis. the python version shouldn't matter. maybe there is something wrong in this line?: https://github.com/conda-forge/occt-feedstock/blob/master/recipe/meta.yaml#L12

**Comment by looooo** [comment]
@scopatz I see two ways to proceed:
1. simple don't skip. ( I can add this for the next PR)
2. skip and remove the skip line in the recipe. I guess it is done this way for the vtk-package.

**Comment by scopatz** [comment]
Looking at the way the [cyclus feedstock](https://github.com/conda-forge/cyclus-feedstock/blob/master/recipe/meta.yaml) does this, it seems that the option 1 is the way to go.

**Comment by jakirkham** [comment]
Wouldn't it just be easier to drop the `skip` before building, we do the same with `qt`. The downside of not keeping the `skip` is that a later re-rendering will add back the Travis CI build and eat up CI time on our already taxed queue. Could I persuade you to do 2? ;)

**Comment by scopatz** [comment]
I don't really understand 2 as it is written. My interpretation is that the skip stays in the recipe, but then we manually delete it when building the mac package. Is that the idea?

**Comment by looooo** [comment]
>My interpretation is that the skip stays in the recipe, but then we manually delete it when building the mac package. Is that the idea?  

yes, that is exactly what I meant. ; )

**Comment by scopatz** [comment]
No worries! I can try it this way!

**Comment by isuruf** [comment]
Btw, I have a test working at https://github.com/conda-forge/occt-feedstock/pull/18 which uses CircleCI for both linux and osx

**Comment by scopatz** [comment]
Alright! I have uploaded the mac package.  Seems to have taken about 1.77 hrs on my machine.

**Comment by looooo** [comment]
thanks! I let this Issue open for further discussion to improve the build time/ switch to conda-build3/ using circleCI...

**Comment by looooo** [comment]
I guess we can close this as we switched osx to circle-ci.
