### ISSUE TITLE
win 32: some symbols of freetype 2.8.1 not found

### ISSUE THREAD

**Issue by looooo** [conda-forge/occt-feedstock#20]
```
error LNK2019: unresolved external symbol _FT_Done_Face referenced in function "class opencascade::handle<class Font_SystemFont> __cdecl checkFont(class opencascade::handle<class Font_FTLibrary> const &,char const * const)"
```
```
warning LNK4272: library machine type 'x64' conflicts with target machine type 'X86'
```

so I skip this for now. I guess it's a problem with the freetype recipe.

**Comment by looooo** [comment]
maybe this is also a problem of the newer conda-build?
@jakirkham @isuruf 

I try to rerender with conda-smithy 2.4.5

**Comment by isuruf** [comment]
Do you have a build log?

**Comment by looooo** [comment]
https://ci.appveyor.com/project/conda-forge/occt-feedstock/build/1.0.35/job/85xnn4y5q4jnk2nm#L2586

**Comment by isuruf** [comment]
cc @msarahan, looks like conda-build is using win-64 packages for a win-32 build

**Comment by looooo** [comment]
conda-forge doesn't support win32 anymore.
