### ISSUE TITLE
VTK modules

### ISSUE THREAD

**Issue by adam-urbanczyk** [conda-forge/occt-feedstock#34]
I'd like to use the VTK integration modules of OCCT. Is there any reason why they are disabled? I think it comes down to specifying
```
-DUSE_VTK:BOOL=ON
```
and adding VTK as a dep. It is already available on conda-forge.

**Comment by looooo** [comment]
I guess it's best to do this after the current iteration https://github.com/conda-forge/occt-feedstock/pull/35. Is there any occt-package available that is built with vtk? I would like to do some tests.

**Comment by adam-urbanczyk** [comment]
No that I know but I will build one locally.

**Comment by adam-urbanczyk** [comment]
I made a pull request #38 , let's continue the discussion there.
