### ISSUE TITLE
move build from user repo to conda-forge

### ISSUE THREAD

**Issue by looooo** [conda-forge/occt-feedstock#47]
@conda-forge/core please copy this build
https://anaconda.org/freecad/occt/files?version=7.4.0
to conda-forge. azure has failed due to missing storage:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=192627&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=11217

**Comment by isuruf** [comment]
You can use `D:` in azure by overriding, `azure: settings_win: variables: CONDA_BLD_PATH: "C:\\bld\\"` in conda-forge.yml and rerendering.

**Comment by looooo** [comment]
D: is already used.
https://github.com/conda-forge/occt-feedstock/blob/4374f9e78292e095d03e305cb3549e71d7638cc7/.azure-pipelines/azure-pipelines-win.yml#L17

**Comment by isuruf** [comment]
Sorry, can you use `C:`?

**Comment by looooo** [comment]
thx

**Comment by isuruf** [comment]
We don't have this documented. Would you be able to send a PR to add this to docs?
