### ISSUE TITLE
label some occt builds as broken (vtk was not pinned correctly)

### ISSUE THREAD

**Issue by looooo** [conda-forge/occt-feedstock#48]
@conda-forge/core please move these packages to broken. 

```
win-64/occt-7.4.0-h823b557_6.tar.bz2
linux-64/occt-7.4.0-h9121d39_6.tar.bz2
osx-64/occt-7.4.0-hb9b6dc7_6.tar.bz2
win-64/occt-7.4.0-h823b557_5.tar.bz2
linux-64/occt-7.4.0-h9121d39_5.tar.bz2
osx-64/occt-7.4.0-hb9b6dc7_5.tar.bz2
osx-64/occt-7.4.0-hb9b6dc7_4.tar.bz2
linux-64/occt-7.4.0-h9121d39_4.tar.bz2
```

![Bildschirmfoto von 2020-08-05 11-49-32](https://user-images.githubusercontent.com/5084704/89398742-cc496780-d711-11ea-81b9-c1a6217571b0.png)

Somehow I cannot find the cf-mark-broken repo? Is it renamed?

**Comment by beckermr** [comment]
See the announcements. It is now called admin-requests

**Comment by jakirkham** [comment]
Addressed in PR ( https://github.com/conda-forge/admin-requests/pull/106 ).
