### ISSUE TITLE
OCCT 7.5 beta

### ISSUE THREAD

**Issue by adam-urbanczyk** [conda-forge/occt-feedstock#50]
OCCT 7.5 beta is out, what would you think about trying to build it here @looooo ?

**Comment by looooo** [comment]
Good idea. Maybe create a branch and using a "dev" or "testung" label?

**Comment by looooo** [comment]
@adam-urbanczyk I created the branch here:
https://github.com/conda-forge/occt-feedstock/tree/rc

but it's expected it to fail, so feel free to create a PR for this branch to further experiment with the build.

**Comment by adam-urbanczyk** [comment]
Solved by #58

**Comment by looooo** [comment]
@adam-urbanczyk  we still need to create a migration for occt 7.5. But I would prefer to wait with this step.
