### ISSUE TITLE
use blobfish patches

### ISSUE THREAD

**Issue by adrianinsaval** [conda-forge/occt-feedstock#86]
### Comment:

As explained in freecad forum https://forum.freecadweb.org/viewtopic.php?f=10&t=66407&start=100#p597687 it would be ideal to use the blobfish patched occt source, they are available here for 7.5.1 https://gitlab.com/blobfish/occt/-/tree/V7_5_1_BF and here for 7.6.2 https://gitlab.com/blobfish/occt/-/tree/V7_6_2_BF I asked him to provide a branch with the patches applied on 7.5.3, in the meantime if you want to test I rebased the patches from 7.5.1 into 7.5.3p2 here: https://gitlab.com/adrianinsaval/occt/-/tree/V7_5_3p2_BF

**Comment by looooo** [comment]
https://github.com/conda-forge/occt-feedstock/pull/87

**Comment by adrianinsaval** [comment]
thanks, should I close this or is there something else left to do?

**Comment by looooo** [comment]
I am not sure. I tried to compile freecad with occt7.6 but windows was failing. I think I am going to use occt7.5 for the 0.20 release and update the weekly builds to occt7.6 once the release is done.

**Comment by adrianinsaval** [comment]
is ifcopenshell with 7.6 working now? and I guess pyocc is not used anymore right? is there somewhere I can see how the build fails?

**Comment by looooo** [comment]
pyocc is not used anymore, but anyway it would be nice to migrate all of the occ-dependent libraries. https://github.com/conda-forge/ifcopenshell-feedstock/pull/20
