### ISSUE TITLE
Create multiple OCCT packages with different number of dependencies (with/without VTK etc.)

### ISSUE THREAD

**Issue by Krande** [conda-forge/occt-feedstock#93]
Hey,

I was wondering if it could make sense to create multiple OCCT packages with varying number of dependencies? The motivation would be to make it possible to reduce the number of dependencies based on what functionality in OCCT you need?

For example, to start, perhaps compile an additional occt version without VTK (which seem to be adding more dependencies than occt itself)?

If this is something that others might find useful, I can start on making a PR with attempting to add a multi-build setup in the meta.yaml. There we can discuss further, such as potential name-conventions etc...

Any thoughts on this? @looooo @adam-urbanczyk

**Comment by looooo** [comment]
It would be interesting to know which package uses the vtk stuff of occt. Maybe we can skip the vtk dependency?

**Comment by Krande** [comment]
FYI: 

    VTK deps:
  
     vtk               9.1.0       qt_py39hf2c8a5a_210 conda-forge/win-64
     eigen             3.2.8       0                   conda-forge/win-64
     tbb-devel         2018.0.4    hdc96acc_0          conda-forge/win-64
     loguru            0.3.2       py36_1              conda-forge/win-64
     utfcpp            2.3.5       0                   conda-forge/win-64
     python            3.9.9       hcf16a7b_0_cpython  conda-forge/win-64
     python_abi        3.9         2_cp39              conda-forge/win-64
     vc                14.3        h3d8a991_9          conda-forge/win-64
     vs2015_runtime    14.32.31332 h1d6e394_9          conda-forge/win-64
     libpng            1.6.38      h19919ed_0          conda-forge/win-64
     libzlib           1.2.13      hcfcfb64_4          conda-forge/win-64
     hdf5              1.12.1      nompi_h57737ce_104  conda-forge/win-64
     freetype          2.12.1      h546665d_0          conda-forge/win-64
     lz4-c             1.9.3       h8ffe710_1          conda-forge/win-64
     jpeg              9e          h8ffe710_2          conda-forge/win-64
     glew              2.1.0       he025d50_0          conda-forge/win-64
     libnetcdf         4.8.1       nompi_hf689e7d_100  conda-forge/win-64
     ffmpeg            4.3.1       ha925a31_0          conda-forge/win-64
     libtiff           4.4.0       hc4061b1_0          conda-forge/win-64
     zlib              1.2.13      hcfcfb64_4          conda-forge/win-64
     pugixml           1.11.4      h0e60522_0          conda-forge/win-64
     libxml2           2.9.14      hf5bbc77_4          conda-forge/win-64
     tbb               2021.7.0    h91493d7_0          conda-forge/win-64
     libtheora         1.1.1       h8d14728_1005       conda-forge/win-64
     qt-main           5.15.6      hf0cf448_0          conda-forge/win-64
     gl2ps             1.4.2       h2c487a6_0          conda-forge/win-64
     expat             2.5.0       h1537add_0          conda-forge/win-64
     libogg            1.3.4       h8ffe710_1          conda-forge/win-64
     proj              9.0.1       h1cfcee9_1          conda-forge/win-64
     jsoncpp           1.9.5       h2d74725_1          conda-forge/win-64
     double-conversion 3.2.0       h63175ca_1          conda-forge/win-64
     sqlite            3.40.0      hcfcfb64_0          conda-forge/win-64
     
and     
     
     OCCT 7.6.2 deps
     
     occt                  7.6.2       h8294837_0          conda-forge/win-64
     fonts-conda-ecosystem 1           0                   conda-forge/noarch
     rapidjson             1.1.0       0                   conda-forge/win-64
     vc                    14.3        h3d8a991_9          conda-forge/win-64
     vs2015_runtime        14.32.31332 h1d6e394_9          conda-forge/win-64
     freetype              2.12.1      h546665d_0          conda-forge/win-64
     freeimage             3.18.0      hfcb8cd7_7          conda-forge/win-64
     vtk                   9.1.0       qt_py39hf2c8a5a_210 conda-forge/win-64
     fontconfig            2.14.1      hbde0cde_0          conda-forge/win-64

and 
    
    OCCT 7.4.0
    
     occt       7.4.0        h823b557_3 conda-forge/win-64
     vc         14.3         h3d8a991_9 conda-forge/win-64
     freetype   2.9.1        hf819b56_4 conda-forge/win-64
     tbb        4.4_20160526 vc9_1      conda-forge/win-64
     tbb        2021.7.0     h91493d7_0 conda-forge/win-64
     fontconfig 2.14.1       hbde0cde_0 conda-forge/win-64

**Comment by adam-urbanczyk** [comment]
Please don't skip it - OCP is using this functionality. Conda build seems to support multiple outputs from a single recipe, maybe this is the best way forward. Only  VTK related artifacts link to VTK, so it would be trivial to split.

**Comment by whophil** [comment]
> It would be interesting to know which package uses the vtk stuff of occt. Maybe we can skip the vtk dependency?

@looooo at the very least, this component does https://dev.opencascade.org/doc/overview/html/occt_user_guides__vis.html

As @adam-urbanczyk states, this component is in use by downstream projects, so the option to retain a VTK-enabled version is critical.

**Comment by Krande** [comment]
From what I can gather, it seems we agree on keeping an occt version with VTK support in addition to a minimum version. That's great! I will try to find some time in the coming days to create a PR for a multi-build meta.yaml. There we can discuss naming conventions for the different variations of occt packages.

**Comment by Krande** [comment]
Hey @looooo :) Some of the build pipelines belonging to conda-forge has suffered some instabilities lately (and it seems our previous build attempt of `occt` failed as a result). I was recommended by one of the conda-forge staff [link](https://matrix.to/#/!SOyumkgPRWoXfQYIFH:matrix.org/$16831168857558cXxof:matrix.org?via=matrix.org&via=gitter.im&via=cadair.com) to just make an empty commit to main. If you have time, maybe you can try it out?
